import Stripe from 'stripe';
import { createClient } from '@supabase/supabase-js';

export function env(name){const v=process.env[name];if(!v)throw new Error(`Missing server environment variable: ${name}`);return v}
export function adminClient(){return createClient(env('SUPABASE_URL'),env('SUPABASE_SECRET_KEY'),{auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}})}
export function stripeClient(){return new Stripe(env('STRIPE_SECRET_KEY'))}
export function originFor(req){const configured=process.env.SITE_URL?.replace(/\/$/,'');if(configured)return configured;const proto=req.headers['x-forwarded-proto']||'https';const host=req.headers['x-forwarded-host']||req.headers.host;return `${proto}://${host}`}
export function send(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(body))}
export function method(req,res,allowed){if(!allowed.includes(req.method)){res.setHeader('Allow',allowed.join(', '));send(res,405,{error:'Method not allowed'});return false}return true}
export async function getUser(req){const auth=req.headers.authorization||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)throw Object.assign(new Error('Sign in required.'),{status:401});const admin=adminClient();const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw Object.assign(new Error('Your sign-in session is invalid or expired.'),{status:401});return {user:data.user,admin}}
export async function requireAdmin(req){const {user,admin}=await getUser(req);const {data,error}=await admin.from('profiles').select('role,account_status').eq('user_id',user.id).single();if(error||data?.role!=='admin')throw Object.assign(new Error('Admin access required.'),{status:403});return {user,admin}}
export function priceForPlan(plan){const key=plan==='starter'?'STRIPE_PRICE_STARTER':plan==='pro'?'STRIPE_PRICE_PRO':'';if(!key)throw Object.assign(new Error('Unknown plan.'),{status:400});return env(key)}
export function setupFeeForPlan(plan){if(plan==='starter')return 16000;if(plan==='pro')return 20000;throw Object.assign(new Error('Unknown plan.'),{status:400})}
export function planFromPrice(priceId){if(priceId&&priceId===process.env.STRIPE_PRICE_STARTER)return 'starter';if(priceId&&priceId===process.env.STRIPE_PRICE_PRO)return 'pro';return null}
export async function parseJson(req){if(req.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;if(typeof req.body==='string')return JSON.parse(req.body||'{}');let raw='';for await(const chunk of req)raw+=chunk;return raw?JSON.parse(raw):{}}
export async function readRawBody(req){const chunks=[];for await(const chunk of req)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));return Buffer.concat(chunks)}
export function errorResponse(res,e){console.error(e);send(res,e.status||500,{error:e.status?e.message:'Server request failed. Check Vercel function logs for details.'})}
export function subscriptionPeriodEnd(sub){const direct=Number(sub.current_period_end)||0;const itemEnds=(sub.items?.data||[]).map(x=>Number(x.current_period_end)||0);return Math.max(direct,...itemEnds,0)}
export async function syncSubscription(admin,sub,userIdHint=null){let userId=userIdHint||sub.metadata?.user_id||null;if(!userId&&sub.customer){const {data}=await admin.from('subscriptions').select('user_id').eq('stripe_customer_id',String(sub.customer)).maybeSingle();userId=data?.user_id||null}if(!userId)return;const item=sub.items?.data?.[0];const price=item?.price;const priceId=price?.id||'';const plan=planFromPrice(priceId)||sub.metadata?.plan||'custom';const end=subscriptionPeriodEnd(sub);const payload={user_id:userId,stripe_customer_id:String(sub.customer||''),stripe_subscription_id:sub.id,status:sub.status||'inactive',plan,price_id:priceId,current_period_end:end?new Date(end*1000).toISOString():null,cancel_at_period_end:!!sub.cancel_at_period_end,unit_amount:price?.unit_amount??null,currency:price?.currency||'eur',interval:price?.recurring?.interval||'month',updated_at:new Date().toISOString()};const {error}=await admin.from('subscriptions').upsert(payload,{onConflict:'user_id'});if(error)throw error}
