-- PlateView production backend
-- Run this whole file in Supabase SQL Editor on a new project.

create extension if not exists pgcrypto;

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  tagline text not null default '',
  currency text not null default 'EUR',
  published boolean not null default false,
  accent text not null default '#b7482d',
  languages text[] not null default array['en','nl','fr']::text[],
  default_language text not null default 'en',
  tables integer not null default 10 check (tables > 0 and tables <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  category text not null default '',
  price numeric(10,2) not null default 0 check (price >= 0),
  available boolean not null default true,
  published boolean not null default true,
  model_url text not null default '',
  photo_url text not null default '',
  allergens text[] not null default '{}'::text[],
  tags text[] not null default '{}'::text[],
  translations jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  event_type text not null check (event_type in ('menu_view','dish_view','ar_launch')),
  session_id uuid,
  table_number integer,
  created_at timestamptz not null default now()
);

create index if not exists restaurants_owner_id_idx on public.restaurants(owner_id);
create index if not exists menu_items_restaurant_id_idx on public.menu_items(restaurant_id);
create index if not exists analytics_events_restaurant_id_idx on public.analytics_events(restaurant_id);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);

alter table public.restaurants enable row level security;
alter table public.menu_items enable row level security;
alter table public.analytics_events enable row level security;

-- Least-privilege Data API grants.
revoke all on public.restaurants from anon, authenticated;
revoke all on public.menu_items from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;

grant select on public.restaurants to anon;
grant select, insert, update, delete on public.restaurants to authenticated;

grant select on public.menu_items to anon;
grant select, insert, update, delete on public.menu_items to authenticated;

grant insert on public.analytics_events to anon;
grant select, insert on public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

-- Restaurant owners can CRUD only their own restaurant rows.
drop policy if exists "owners_select_restaurants" on public.restaurants;

create policy "owners_select_restaurants"
on public.restaurants for select to authenticated
using (owner_id = (select auth.uid()));

drop policy if exists "owners_insert_restaurants" on public.restaurants;

create policy "owners_insert_restaurants"
on public.restaurants for insert to authenticated
with check (owner_id = (select auth.uid()));

drop policy if exists "owners_update_restaurants" on public.restaurants;

create policy "owners_update_restaurants"
on public.restaurants for update to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

drop policy if exists "owners_delete_restaurants" on public.restaurants;

create policy "owners_delete_restaurants"
on public.restaurants for delete to authenticated
using (owner_id = (select auth.uid()));

-- Anyone may read only published restaurants.
drop policy if exists "public_read_published_restaurants" on public.restaurants;

create policy "public_read_published_restaurants"
on public.restaurants for select to anon
using (published = true);

-- Owners can manage items only inside restaurants they own.
drop policy if exists "owners_select_menu_items" on public.menu_items;

create policy "owners_select_menu_items"
on public.menu_items for select to authenticated
using (exists (
  select 1 from public.restaurants r
  where r.id = restaurant_id and r.owner_id = (select auth.uid())
));

drop policy if exists "owners_insert_menu_items" on public.menu_items;

create policy "owners_insert_menu_items"
on public.menu_items for insert to authenticated
with check (exists (
  select 1 from public.restaurants r
  where r.id = restaurant_id and r.owner_id = (select auth.uid())
));

drop policy if exists "owners_update_menu_items" on public.menu_items;

create policy "owners_update_menu_items"
on public.menu_items for update to authenticated
using (exists (
  select 1 from public.restaurants r
  where r.id = restaurant_id and r.owner_id = (select auth.uid())
))
with check (exists (
  select 1 from public.restaurants r
  where r.id = restaurant_id and r.owner_id = (select auth.uid())
));

drop policy if exists "owners_delete_menu_items" on public.menu_items;

create policy "owners_delete_menu_items"
on public.menu_items for delete to authenticated
using (exists (
  select 1 from public.restaurants r
  where r.id = restaurant_id and r.owner_id = (select auth.uid())
));

-- Guests may read items only when both item and restaurant are published.
drop policy if exists "public_read_published_menu_items" on public.menu_items;

create policy "public_read_published_menu_items"
on public.menu_items for select to anon
using (
  published = true and
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.published = true
  )
);

-- Anonymous analytics writes only for a published restaurant.
drop policy if exists "public_insert_analytics" on public.analytics_events;

create policy "public_insert_analytics"
on public.analytics_events for insert to anon
with check (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.published = true
  )
);

drop policy if exists "owner_insert_analytics" on public.analytics_events;

create policy "owner_insert_analytics"
on public.analytics_events for insert to authenticated
with check (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.owner_id = (select auth.uid())
  )
);

drop policy if exists "owner_read_analytics" on public.analytics_events;

create policy "owner_read_analytics"
on public.analytics_events for select to authenticated
using (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.owner_id = (select auth.uid())
  )
);

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

drop trigger if exists restaurants_set_updated_at on public.restaurants;
create trigger restaurants_set_updated_at before update on public.restaurants
for each row execute function public.set_updated_at();

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at before update on public.menu_items
for each row execute function public.set_updated_at();

-- Public storage bucket for dish photos + GLB files.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'menu-assets',
  'menu-assets',
  true,
  104857600,
  array[
    'model/gltf-binary',
    'application/octet-stream',
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/avif'
  ]
)
on conflict (id) do update set public = excluded.public;

-- Authenticated users can upload only below their own UID prefix.
drop policy if exists "asset_owner_insert" on storage.objects;

create policy "asset_owner_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'menu-assets'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

-- Needed so Storage can return uploaded object metadata.
drop policy if exists "asset_owner_select" on storage.objects;

create policy "asset_owner_select"
on storage.objects for select to authenticated
using (
  bucket_id = 'menu-assets'
  and (
    owner_id = (select auth.uid())::text
    or (storage.foldername(name))[1] = (select auth.uid())::text
  )
);

drop policy if exists "asset_owner_update" on storage.objects;

create policy "asset_owner_update"
on storage.objects for update to authenticated
using (
  bucket_id = 'menu-assets'
  and owner_id = (select auth.uid())::text
)
with check (
  bucket_id = 'menu-assets'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "asset_owner_delete" on storage.objects;

create policy "asset_owner_delete"
on storage.objects for delete to authenticated
using (
  bucket_id = 'menu-assets'
  and owner_id = (select auth.uid())::text
);

-- The bucket is public, so public object delivery is handled by Storage's public URL.
