const $=s=>document.querySelector(s);let adminData=null;const money=c=>new Intl.NumberFormat('en-BE',{style:'currency',currency:'EUR'}).format((Number(c)||0)/100);
function statusClass(v){return ['active','trialing','legacy'].includes(v)?'good':['suspended','canceled','past_due','unpaid','inactive'].includes(v)?'bad':''}
function render(){if(!adminData)return;const t=adminData.totals;$('#adminStats').innerHTML=[['Restaurants',t.restaurants],['Active subscriptions',t.active_subscriptions],['MRR',money(t.mrr_cents)],['Menu views',t.menu_views]].map(([l,v])=>`<article class="stat"><small>${l}</small><strong>${v}</strong></article>`).join('');renderRows()}
function renderRows(){const q=$('#accountSearch').value.toLowerCase();const rows=(adminData.accounts||[]).filter(a=>!q||a.email.toLowerCase().includes(q)||(a.restaurants||[]).some(r=>r.name.toLowerCase().includes(q)));$('#accountRows').innerHTML=rows.map(a=>{const sub=a.subscription||{};const rests=a.restaurants||[];return `<tr><td data-label="Account"><b>${a.email||'No email'}</b><small>${a.role}</small></td><td data-label="Restaurants"><b>${rests.length}</b><small>${rests.slice(0,2).map(r=>r.name).join(', ')||'No restaurant yet'}</small></td><td data-label="Plan"><span class="pill">${sub.plan||'none'}</span></td><td data-label="Subscription"><span class="pill ${statusClass(sub.status)}">${sub.status||'inactive'}</span></td><td data-label="Account status"><span class="pill ${statusClass(a.account_status)}">${a.account_status}</span></td><td data-label="Action">${a.role==='admin'?'Admin':`<button class="action ${a.account_status==='active'?'danger':''}" data-user="${a.user_id}" data-action="${a.account_status==='active'?'suspend':'restore'}">${a.account_status==='active'?'Suspend':'Restore'}</button>`}</td></tr>`}).join('')||'<tr><td colspan="6">No matching accounts.</td></tr>';document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>changeAccount(b))}
async function load(){const note=$('#adminMessage');note.classList.remove('hidden');note.textContent='Loading admin data…';try{adminData=await ARAPP.apiWithAuth('/api/admin-overview',{method:'GET'});note.classList.add('hidden');render()}catch(e){note.textContent=e.message+' Make sure your profile role is set to admin in Supabase.'}}
async function changeAccount(btn){const action=btn.dataset.action;if(!confirm(`${action==='suspend'?'Suspend':'Restore'} this account?`))return;btn.disabled=true;try{await ARAPP.apiWithAuth('/api/admin-account',{method:'POST',body:JSON.stringify({user_id:btn.dataset.user,action})});await load()}catch(e){alert(e.message);btn.disabled=false}}
$('#accountSearch').oninput=renderRows;$('#refreshAdmin').onclick=load;
const adminSignOut=async()=>{await ARAPP.signOut();location.href='auth.html?mode=login'};
$('#adminSignOut').onclick=adminSignOut;
if($('#adminMobileSignOut'))$('#adminMobileSignOut').onclick=adminSignOut;
(async()=>{if(!ARAPP.configured){$('#adminMessage').textContent='Supabase is not configured.';return}const s=await ARAPP.session();if(!s){location.href='auth.html?mode=login';return}await load()})();
