const $=s=>document.querySelector(s);let step=1,restaurant=null,firstDish=null;let logoFile=null,heroFile=null,modelFile=null,photoFile=null;
const msg=t=>{const el=$('#wizardMessage');if(el)el.textContent=t||'';};
function field(label,id,value='',type='text',extra=''){return `<div class="field"><label>${label}</label><input id="${id}" type="${type}" value="${String(value||'').replaceAll('&','&amp;').replaceAll('"','&quot;')}" ${extra}></div>`}
function render(){$('#progressBar').style.width=`${step*20}%`;$('#stepLabel').textContent=`STEP ${step} OF 5`;$('#backBtn').style.visibility=step===1?'hidden':'visible';$('#nextBtn').textContent=step===5?'Open dashboard':'Continue';msg('');const body=$('#wizardBody');
 if(step===1){body.innerHTML=`<h1>Your restaurant.</h1><p>Start with the basics. You can change all of this later.</p>${field('Restaurant name','restName',restaurant?.name||'','text','required')}${field('Menu URL slug','restSlug',restaurant?.slug||'')}${field('Tagline','restTagline',restaurant?.tagline||'Explore our menu in 3D and AR.')}${field('Accent color','restAccent',restaurant?.accent||'#b7482d','color')}`;$('#restName').addEventListener('input',()=>{if(!restaurant&&!$('#restSlug').dataset.touched)$('#restSlug').value=ARAPP.slugify($('#restName').value)});$('#restSlug').addEventListener('input',()=>$('#restSlug').dataset.touched='1')}
 if(step===2){body.innerHTML=`<h1>Make it yours.</h1><p>Add restaurant branding. You can skip either upload and return later.</p><div class="two-col"><div class="upload-box"><b>Restaurant logo</b><p>Square PNG, JPG or WebP works best.</p><input id="logoFile" type="file" accept="image/*"></div><div class="upload-box"><b>Hero image</b><p>Optional restaurant or food cover image.</p><input id="heroFile" type="file" accept="image/*"></div></div><div class="field"><label>Hero style</label><select id="heroMode"><option value="3d" ${(restaurant?.hero_mode||'3d')==='3d'?'selected':''}>Featured 3D dish</option><option value="image" ${restaurant?.hero_mode==='image'?'selected':''}>Uploaded hero image</option></select></div>`;$('#logoFile').onchange=e=>logoFile=e.target.files[0]||null;$('#heroFile').onchange=e=>heroFile=e.target.files[0]||null}
 if(step===3){body.innerHTML=`<h1>Add your first dish.</h1><p>This gives the menu something real to show. You may also skip the 3D model and add it later.</p><div class="two-col">${field('Dish name','dishName','')}${field('Category','dishCategory','Mains')}</div><div class="two-col">${field('Price (€)','dishPrice','15','number','min="0" step="0.1"')}${field('Real dish width (cm)','dishWidth','24','number','min="1" step="0.5"')}</div>${field('Description','dishDescription','')}<div class="two-col"><div class="upload-box"><b>3D model (.glb)</b><p>Used for 3D and AR.</p><input id="modelFile" type="file" accept=".glb,model/gltf-binary"></div><div class="upload-box"><b>Dish photo</b><p>Optional fallback preview.</p><input id="photoFile" type="file" accept="image/*"></div></div>`;$('#modelFile').onchange=e=>modelFile=e.target.files[0]||null;$('#photoFile').onchange=e=>photoFile=e.target.files[0]||null}
 if(step===4){body.innerHTML=`<h1>Set up your tables.</h1><p>PlateView creates a unique QR link per table so scans can also appear in analytics.</p>${field('Number of tables','tableCount',restaurant?.tables||10,'number','min="1" max="1000"')}<div class="upload-box"><b>Ready to publish?</b><p>Publishing makes the guest menu accessible. You can unpublish it from the dashboard at any time.</p><label style="display:flex;gap:10px;align-items:center"><input id="publishNow" type="checkbox" checked> Publish menu now</label></div>`}
 if(step===5){const url=restaurant?new URL(`menu.html?r=${encodeURIComponent(restaurant.slug)}&table=1`,location.href).href:'';body.innerHTML=`<div class="success-panel"><span class="eyebrow">YOUR MENU IS READY</span><h1>Put it on the table.</h1><p>Your restaurant dashboard is set up. This is the Table 1 QR code; the dashboard can generate and print every table.</p><div class="qr-mini" id="onboardingQr"></div><p><b>${restaurant?.name||''}</b><br><span style="color:var(--muted)">Table 1</span></p><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><a class="btn" target="_blank" href="${url}">Open live menu ↗</a><a class="btn primary" href="dashboard.html">Open dashboard</a></div></div>`;$('#backBtn').style.visibility='hidden';$('#nextBtn').classList.add('hidden');if(window.QRCode&&url)new QRCode($('#onboardingQr'),{text:url,width:180,height:180,correctLevel:QRCode.CorrectLevel.M})}
}
async function saveStep(){msg('Saving…');if(step===1){const nameEl=$('#restName'),slugEl=$('#restSlug'),taglineEl=$('#restTagline'),accentEl=$('#restAccent');if(!nameEl||!slugEl||!taglineEl||!accentEl){render();throw new Error('The setup form was not ready yet. Please try Continue again.');}const name=nameEl.value.trim();if(!name)throw new Error('Restaurant name is required.');const patch={name,slug:ARAPP.slugify(slugEl.value||name),tagline:taglineEl.value.trim(),accent:accentEl.value};if(restaurant)restaurant=await ARAPP.updateRestaurant(restaurant.id,patch);else restaurant=await ARAPP.createRestaurant(patch)}
 else if(step===2){if(!restaurant)throw new Error('Create the restaurant first.');let logo=restaurant.logo_url||'',hero=restaurant.hero_image_url||'';if(logoFile)logo=await ARAPP.uploadAsset(logoFile,restaurant.id,'branding/logo');if(heroFile)hero=await ARAPP.uploadAsset(heroFile,restaurant.id,'branding/hero');restaurant=await ARAPP.updateRestaurant(restaurant.id,{logo_url:logo,hero_image_url:hero,hero_mode:$('#heroMode').value})}
 else if(step===3){const name=$('#dishName').value.trim();if(!name){msg('No dish added yet — you can add one from the dashboard.');return}let model='',photo='';if(modelFile)model=await ARAPP.uploadAsset(modelFile,restaurant.id,'models');if(photoFile)photo=await ARAPP.uploadAsset(photoFile,restaurant.id,'photos');const width=Number($('#dishWidth').value)||0;firstDish=await ARAPP.saveMenuItem({restaurant_id:restaurant.id,category:$('#dishCategory').value.trim()||'Mains',price:Number($('#dishPrice').value)||0,available:true,published:true,model_url:model,photo_url:photo,allergens:[],tags:[],translations:{en:{name,description:$('#dishDescription').value.trim()},nl:{name:'',description:''},fr:{name:'',description:''},_meta:width?{width_cm:width}:{}},sort_order:0})}
 else if(step===4){restaurant=await ARAPP.updateRestaurant(restaurant.id,{tables:Math.max(1,Number($('#tableCount').value)||1),published:$('#publishNow').checked})}msg('')}
$('#nextBtn').onclick=async()=>{if(step===5){location.href='dashboard.html';return}const b=$('#nextBtn');b.disabled=true;b.textContent='Saving…';try{await saveStep();step++;render()}catch(e){msg(e.message)}finally{b.disabled=false;if(step<5)b.textContent='Continue'}};$('#backBtn').onclick=()=>{if(step>1){step--;render()}};
async function waitForSubscription(){const q=new URLSearchParams(location.search);const sessionId=q.get('session_id');const checkoutSuccess=q.get('checkout')==='success';if(checkoutSuccess&&sessionId){try{msg('Confirming your Stripe subscription…');const confirmed=await ARAPP.apiWithAuth('/api/confirm-checkout',{method:'POST',body:JSON.stringify({session_id:sessionId})});if(['active','trialing','legacy'].includes(confirmed?.status)){return {signedIn:true,allowed:true,reason:'checkout_confirmed',profile:null,subscription:{status:confirmed.status}}}}catch(e){console.warn('Checkout confirmation is waiting for Stripe/webhook',e)}}for(let i=0;i<12;i++){const a=await ARAPP.accountAccess();if(a.allowed)return a;if(!checkoutSuccess)return a;msg('Activating your subscription…');await new Promise(r=>setTimeout(r,1600))}return ARAPP.accountAccess()}
(async()=>{if(!ARAPP.configured){msg('Supabase is not configured.');$('#nextBtn').disabled=true;return}const s=await ARAPP.session();if(!s){location.href='auth.html?mode=login';return}render();msg('Activating your subscription…');const access=await waitForSubscription();if(!access.allowed){if(new URLSearchParams(location.search).get('checkout')==='success'){msg('Your payment succeeded, but PlateView is still activating your account. Refresh this page in a few seconds or use Go to dashboard.');$('#nextBtn').disabled=false;return}location.href='pricing.html?subscription=required';return}const rs=await ARAPP.restaurantsForOwner();if(rs.length)restaurant=rs[0];render()})().catch(e=>{console.error('Onboarding error',e);render();msg(e?.message||'Something went wrong while loading setup.');});
